### ISSUE TITLE
Unable to use generator: Error unexpected end of JSON input - All the time

### ISSUE THREAD

**Issue by dilfuza97** [slsa-framework/slsa-jenkins-generator#14]
here is the out put:

./generator -a artifacts/test.jar -o artifacts
2023/01/22 19:07:10 unexpected end of JSON input

-----------------------
+ docker run --env-file ./envlist -v /Users/dilfuzaibaidullaeva/.jenkins/workspace/pipeline-salsa:/artifacts scia:slsa-generator -a artifacts/output.json -o artifacts
2023/01/22 18:38:43 unexpected end of JSON input
[Pipeline] }

**Comment by dongheelee92** [comment]
Please check if the github webhook settings are correct. Extracts information from the github payload, but throws an error if the github payload is empty.
